/**
 * MongoDB indexes. createIndex is idempotent, so this runs on every boot.
 * Unique indexes double as the app's integrity rules (one rating per user per post, one stake per take, …).
 */
export async function ensureIndexes(db) {
  const idx = (col, spec, opts = {}) => db[col].raw.createIndex(spec, opts);
  await Promise.all([
    idx('users', { email: 1 }, { unique: true, partialFilterExpression: { email: { $type: 'string' } } }),
    idx('users', { handleLower: 1 }, { unique: true }),
    idx('users', { isAi: 1, deletedAt: 1 }),
    idx('users', { 'boost.until': 1 }, { sparse: true }),
    idx('users', { xp: -1 }),
    idx('users', { streakDays: -1 }),
    idx('follows', { followerId: 1, followeeId: 1 }, { unique: true }),
    idx('follows', { followeeId: 1 }),
    idx('blocks', { blockerId: 1, blockedId: 1 }, { unique: true }),
    idx('blocks', { blockedId: 1 }),
    idx('posts', { hidden: 1, createdAt: -1 }),
    idx('posts', { authorId: 1, createdAt: -1 }),
    idx('posts', { dropId: 1, authorId: 1 }),
    idx('posts', { tags: 1, createdAt: -1 }),
    idx('battleVotes', { postId: 1, userId: 1 }, { unique: true }),
    idx('ratings', { postId: 1, userId: 1 }, { unique: true }),
    idx('ratings', { userId: 1, createdAt: -1 }),
    idx('reactions', { postId: 1, userId: 1 }, { unique: true }),
    idx('comments', { postId: 1, createdAt: 1 }),
    idx('comments', { authorId: 1, postId: 1 }),
    idx('hotTakes', { resolved: 1, endsAt: 1 }),
    idx('stakes', { takeId: 1, userId: 1 }, { unique: true }),
    idx('stakes', { userId: 1 }),
    idx('threads', { boardId: 1, lastActivityAt: -1 }),
    idx('threads', { lastActivityAt: -1 }),
    idx('threadVotes', { threadId: 1, userId: 1 }, { unique: true }),
    idx('replies', { threadId: 1, createdAt: 1 }),
    idx('conversations', { 'members.userId': 1, updatedAt: -1 }),
    idx('conversations', { pairKey: 1 }, { unique: true, partialFilterExpression: { pairKey: { $type: 'string' } } }),
    idx('messages', { roomType: 1, roomId: 1, createdAt: -1 }),
    idx('notifications', { userId: 1, createdAt: -1 }),
    idx('inventory', { userId: 1, itemId: 1 }, { unique: true }),
    idx('streams', { endedAt: 1, giftsTotal: -1 }),
    idx('streams', { hostId: 1, endedAt: 1 }),
    idx('streamGifts', { streamId: 1 }),
    idx('pushTokens', { userId: 1 }),
    idx('reports', { targetType: 1, targetId: 1 }),
    idx('emailTokens', { userId: 1, kind: 1 }),
    // Housekeeping: expired single-use tokens and old daily counters clean themselves up.
    idx('emailTokens', { expiresAtDate: 1 }, { expireAfterSeconds: 7 * 86_400 }),
    idx('dailyCounters', { at: 1 }, { expireAfterSeconds: 14 * 86_400 }),
    idx('purchases', { userId: 1, createdAt: -1 }),
    idx('shouts', { hidden: 1, createdAt: -1 }),
    idx('shouts', { authorId: 1, createdAt: -1 }),
    idx('shoutReactions', { shoutId: 1, userId: 1 }, { unique: true }),
    idx('contentReactions', { type: 1, targetId: 1, userId: 1 }, { unique: true }),
    idx('arenas', { status: 1, visibility: 1, createdAt: -1 }),
    idx('arenas', { status: 1, turnDeadline: 1 }),
    idx('arenas', { seats: 1, status: 1 }),
    idx('arenas', { code: 1 }, { unique: true }),
    idx('users', { refCode: 1 }, { unique: true, sparse: true }),
    idx('arcadeRuns', { game: 1, status: 1, score: -1 }),
    idx('tournaments', { kind: 1, game: 1, endsAt: 1 }),
    idx('tournamentEntries', { tournamentId: 1, userId: 1 }, { unique: true }),
    idx('tournamentEntries', { tournamentId: 1, score: -1 }),
    idx('arcadeRuns', { userId: 1, game: 1, score: -1 }),
    idx('users', { referredById: 1, createdAt: -1 }, { sparse: true }),
    idx('wallNotes', { profileId: 1, createdAt: -1 }),
    idx('modEvents', { userId: 1, createdAt: -1 }),
    idx('modFlags', { status: 1, priority: 1, createdAt: -1 }),
    idx('reports', { status: 1, createdAt: -1 }),
    idx('profileRatings', { profileId: 1, userId: 1 }, { unique: true }),
    idx('profileViews', { profileId: 1, viewerId: 1, day: 1 }, { unique: true }),
    idx('profileViews', { profileId: 1, at: -1 }),
    idx('shouts', { mentions: 1, createdAt: -1 }),
    // Shared state (rate limits, cooldowns, leases…) expires on its own; cluster events are kept for a few minutes.
    // Profile showcase lists (followers / following / friends, threads).
    idx('follows', { followeeId: 1, createdAt: -1 }),
    idx('follows', { followerId: 1, createdAt: -1 }),
    idx('threads', { authorId: 1, createdAt: -1 }),
    // Natural keys of records whose _id is an ObjectId.
    idx('boards', { slug: 1 }, { unique: true, partialFilterExpression: { slug: { $type: 'string' } } }),
    idx('lounges', { slug: 1 }, { unique: true, partialFilterExpression: { slug: { $type: 'string' } } }),
    idx('storeItems', { key: 1 }, { unique: true, partialFilterExpression: { key: { $type: 'string' } } }),
    idx('drops', { day: 1 }, { unique: true, partialFilterExpression: { day: { $type: 'string' } } }),
    idx('emailTokens', { tokenHash: 1 }, { unique: true, partialFilterExpression: { tokenHash: { $type: 'string' } } }),
    idx('pushTokens', { token: 1 }, { unique: true, partialFilterExpression: { token: { $type: 'string' } } }),
    idx('dailyCounters', { userId: 1, day: 1, key: 1 }, { unique: true }),
    idx('posts', { systemKey: 1 }, { unique: true, partialFilterExpression: { systemKey: { $type: 'string' } } }),
    idx('purchases', { providerTxId: 1 }, { unique: true, partialFilterExpression: { providerTxId: { $type: 'string' } } }),
    idx('users', { legacyId: 1 }, { partialFilterExpression: { legacyId: { $type: 'string' } } }),
    idx('users', { personaId: 1 }, { unique: true, partialFilterExpression: { personaId: { $type: 'string' } } }),
    // Friends
    idx('friendRequests', { fromId: 1, toId: 1 }, { unique: true }),
    idx('friendRequests', { toId: 1, status: 1, createdAt: -1 }),
    idx('friendships', { a: 1, b: 1 }, { unique: true }),
    idx('friendships', { b: 1 }),
    // Clans: one clan per member, unique names and tags
    idx('clanMembers', { userId: 1 }, { unique: true }),
    idx('clanMembers', { clanId: 1, rep: -1 }),
    idx('clans', { nameLower: 1 }, { unique: true }),
    idx('clans', { tag: 1 }, { unique: true }),
    idx('clans', { rep: -1 }),
    idx('clanRequests', { clanId: 1, userId: 1 }, { unique: true }),
    idx('clanWars', { status: 1, endsAt: 1 }),
    idx('clanWeeks', { week: 1, clanId: 1 }, { unique: true }),
    idx('kv', { exp: 1 }, { expireAfterSeconds: 0 }),
    idx('busEvents', { at: 1 }, { expireAfterSeconds: 300 }),
    idx('socketEvents', { createdAt: 1 }, { expireAfterSeconds: 300 }),
  ]);
}
