/** Trivia questions: [category, question, correct answer, three wrong answers]. */
export const TRIVIA_BANK = [
  ['Geography', 'What is the capital of Australia?', 'Canberra', 'Sydney', 'Melbourne', 'Perth'],
  ['Geography', 'Which river flows through Cairo?', 'The Nile', 'The Tigris', 'The Congo', 'The Niger'],
  ['Geography', 'Mount Kilimanjaro is in which country?', 'Tanzania', 'Kenya', 'Uganda', 'Ethiopia'],
  ['Geography', 'What is the largest ocean?', 'Pacific', 'Atlantic', 'Indian', 'Arctic'],
  ['Geography', 'Which country has the most islands?', 'Sweden', 'Indonesia', 'Philippines', 'Japan'],
  ['Geography', 'What is the smallest country in the world?', 'Vatican City', 'Monaco', 'San Marino', 'Malta'],
  ['Geography', 'Which desert is the largest hot desert?', 'Sahara', 'Gobi', 'Kalahari', 'Arabian'],
  ['Geography', 'Reykjavik is the capital of…', 'Iceland', 'Norway', 'Finland', 'Greenland'],
  ['Geography', 'Which US state is the Grand Canyon in?', 'Arizona', 'Nevada', 'Utah', 'Colorado'],
  ['Geography', 'Which city is known as the Big Apple?', 'New York', 'Chicago', 'Los Angeles', 'Boston'],
  ['Geography', 'The Andes run along which continent?', 'South America', 'Africa', 'Asia', 'Europe'],
  ['Geography', 'What is the capital of Canada?', 'Ottawa', 'Toronto', 'Vancouver', 'Montreal'],
  ['Science', 'What gas do plants take in for photosynthesis?', 'Carbon dioxide', 'Oxygen', 'Nitrogen', 'Hydrogen'],
  ['Science', 'What is H2O better known as?', 'Water', 'Hydrogen peroxide', 'Salt', 'Ozone'],
  ['Science', 'Which planet is closest to the Sun?', 'Mercury', 'Venus', 'Mars', 'Earth'],
  ['Science', 'How many bones are in the adult human body?', '206', '186', '226', '256'],
  ['Science', 'What is the chemical symbol for gold?', 'Au', 'Ag', 'Gd', 'Go'],
  ['Science', 'What is the hardest natural substance?', 'Diamond', 'Quartz', 'Iron', 'Granite'],
  ['Science', 'Which planet is known as the Red Planet?', 'Mars', 'Jupiter', 'Saturn', 'Venus'],
  ['Science', 'What part of the cell holds DNA?', 'Nucleus', 'Ribosome', 'Membrane', 'Mitochondria'],
  ['Science', 'Light travels at about how many km per second?', '300,000', '30,000', '3,000', '3 million'],
  ['Science', 'Which organ pumps blood around the body?', 'Heart', 'Liver', 'Lungs', 'Kidneys'],
  ['Science', 'What is the largest planet in our solar system?', 'Jupiter', 'Saturn', 'Neptune', 'Earth'],
  ['Science', 'Which vitamin do we get from sunlight?', 'Vitamin D', 'Vitamin C', 'Vitamin A', 'Vitamin B12'],
  ['Science', 'What is the boiling point of water at sea level in °C?', '100', '90', '110', '120'],
  ['Science', 'Which element has the symbol O?', 'Oxygen', 'Osmium', 'Gold', 'Oganesson'],
  ['History', 'In which year did World War II end?', '1945', '1939', '1918', '1950'],
  ['History', 'Who was the first person to walk on the Moon?', 'Neil Armstrong', 'Buzz Aldrin', 'Yuri Gagarin', 'John Glenn'],
  ['History', 'The Great Wall is in which country?', 'China', 'Mongolia', 'Japan', 'India'],
  ['History', 'Who painted the Mona Lisa?', 'Leonardo da Vinci', 'Michelangelo', 'Raphael', 'Van Gogh'],
  ['History', 'Which ship sank in 1912 after hitting an iceberg?', 'Titanic', 'Lusitania', 'Britannic', 'Queen Mary'],
  ['History', 'Who was the first President of the United States?', 'George Washington', 'Abraham Lincoln', 'Thomas Jefferson', 'John Adams'],
  ['History', 'The Berlin Wall fell in which year?', '1989', '1991', '1979', '1961'],
  ['History', 'Which ancient people built Machu Picchu?', 'The Inca', 'The Maya', 'The Aztecs', 'The Olmecs'],
  ['History', 'Who was known as the Iron Lady?', 'Margaret Thatcher', 'Angela Merkel', 'Indira Gandhi', 'Golda Meir'],
  ['History', 'The pyramids of Giza are in which country?', 'Egypt', 'Sudan', 'Mexico', 'Iraq'],
  ['History', 'What year did the first iPhone come out?', '2007', '2005', '2009', '2010'],
  ['Pop culture', 'Which band sang "Bohemian Rhapsody"?', 'Queen', 'The Beatles', 'Led Zeppelin', 'ABBA'],
  ['Pop culture', 'Who plays Iron Man in the Marvel films?', 'Robert Downey Jr.', 'Chris Evans', 'Chris Hemsworth', 'Mark Ruffalo'],
  ['Pop culture', 'Which wizard school does Harry Potter attend?', 'Hogwarts', 'Durmstrang', 'Beauxbatons', 'Ilvermorny'],
  ['Pop culture', 'Which artist released the album "1989"?', 'Taylor Swift', 'Adele', 'Beyoncé', 'Katy Perry'],
  ['Pop culture', 'What colour is SpongeBob’s best friend Patrick?', 'Pink', 'Blue', 'Green', 'Yellow'],
  ['Pop culture', 'Which video game features a plumber named Mario?', 'Super Mario Bros.', 'Sonic', 'Zelda', 'Pac-Man'],
  ['Pop culture', 'Who sang "Thriller"?', 'Michael Jackson', 'Prince', 'Madonna', 'Whitney Houston'],
  ['Pop culture', 'Which streaming show is set in Hawkins, Indiana?', 'Stranger Things', 'Dark', 'The OA', 'Riverdale'],
  ['Pop culture', 'What is the name of Simba’s father?', 'Mufasa', 'Scar', 'Rafiki', 'Zazu'],
  ['Pop culture', 'Which K-pop group sang "Dynamite"?', 'BTS', 'BLACKPINK', 'EXO', 'TWICE'],
  ['Pop culture', 'Which game has creepers and diamonds?', 'Minecraft', 'Roblox', 'Fortnite', 'Terraria'],
  ['Pop culture', 'Who is Batman’s secret identity?', 'Bruce Wayne', 'Clark Kent', 'Peter Parker', 'Tony Stark'],
  ['Sports', 'How many players are on a football (soccer) team on the pitch?', '11', '10', '9', '12'],
  ['Sports', 'Which country won the 2022 FIFA World Cup?', 'Argentina', 'France', 'Brazil', 'Croatia'],
  ['Sports', 'In tennis, what is a score of zero called?', 'Love', 'Nil', 'Zero', 'Duck'],
  ['Sports', 'How many rings are on the Olympic flag?', '5', '4', '6', '7'],
  ['Sports', 'Which sport uses a shuttlecock?', 'Badminton', 'Squash', 'Tennis', 'Table tennis'],
  ['Sports', 'How many points is a touchdown worth?', '6', '7', '3', '5'],
  ['Sports', 'Which country hosts the Tour de France?', 'France', 'Italy', 'Spain', 'Belgium'],
  ['Sports', 'What is the maximum break in snooker?', '147', '155', '140', '160'],
  ['Sports', 'Usain Bolt is famous for which event?', 'Sprinting', 'Long jump', 'Marathon', 'Swimming'],
  ['Sports', 'Which club is nicknamed the Red Devils?', 'Manchester United', 'Liverpool', 'Arsenal', 'AC Milan'],
  ['Food', 'Which country is sushi from?', 'Japan', 'China', 'Korea', 'Thailand'],
  ['Food', 'What is the main ingredient in guacamole?', 'Avocado', 'Peas', 'Lime', 'Tomato'],
  ['Food', 'Which nut is used to make marzipan?', 'Almond', 'Cashew', 'Walnut', 'Peanut'],
  ['Food', 'What kind of pasta is shaped like little ears?', 'Orecchiette', 'Farfalle', 'Penne', 'Fusilli'],
  ['Food', 'Which fruit has its seeds on the outside?', 'Strawberry', 'Raspberry', 'Kiwi', 'Fig'],
  ['Food', 'Paella comes from which country?', 'Spain', 'Italy', 'Portugal', 'Mexico'],
  ['Food', 'What is the most widely eaten fish in the world?', 'Tuna', 'Salmon', 'Cod', 'Sardine'],
  ['Food', 'Which spice is the most expensive by weight?', 'Saffron', 'Vanilla', 'Cardamom', 'Cinnamon'],
  ['Food', 'Kimchi is mainly made from…', 'Cabbage', 'Radish', 'Cucumber', 'Carrot'],
  ['Food', 'Which drink is made from fermented tea?', 'Kombucha', 'Kefir', 'Kvass', 'Matcha'],
  ['Tech', 'What does "www" stand for?', 'World Wide Web', 'Wide World Web', 'Web World Wide', 'World Web Wide'],
  ['Tech', 'Who co-founded Apple with Steve Wozniak?', 'Steve Jobs', 'Bill Gates', 'Elon Musk', 'Larry Page'],
  ['Tech', 'What does CPU stand for?', 'Central Processing Unit', 'Computer Power Unit', 'Core Program Utility', 'Central Program Unit'],
  ['Tech', 'Which company makes the PlayStation?', 'Sony', 'Microsoft', 'Nintendo', 'Sega'],
  ['Tech', 'What is the most used search engine?', 'Google', 'Bing', 'Yahoo', 'DuckDuckGo'],
  ['Tech', 'Which language styles web pages?', 'CSS', 'HTML', 'SQL', 'Python'],
  ['Tech', 'What does "AI" stand for?', 'Artificial Intelligence', 'Automated Input', 'Advanced Internet', 'Analog Interface'],
  ['Tech', 'How many bits are in a byte?', '8', '4', '16', '10'],
  ['Tech', 'What year was the first email sent (roughly)?', '1971', '1981', '1991', '1965'],
  ['Animals', 'What is the fastest land animal?', 'Cheetah', 'Lion', 'Horse', 'Greyhound'],
  ['Animals', 'How many legs does a spider have?', '8', '6', '10', '12'],
  ['Animals', 'Which mammal can fly?', 'Bat', 'Flying squirrel', 'Sugar glider', 'Colugo'],
  ['Animals', 'What do you call a baby kangaroo?', 'Joey', 'Kit', 'Cub', 'Pup'],
  ['Animals', 'Which animal is the largest on Earth?', 'Blue whale', 'Elephant', 'Giraffe', 'Great white shark'],
  ['Animals', 'Which bird is a symbol of peace?', 'Dove', 'Eagle', 'Swan', 'Owl'],
  ['Animals', 'How many hearts does an octopus have?', '3', '1', '2', '4'],
  ['Animals', 'Pandas mostly eat…', 'Bamboo', 'Fish', 'Berries', 'Insects'],
  ['Animals', 'Which animal never sleeps lying down and lives in herds?', 'Giraffe', 'Wolf', 'Bear', 'Lion'],
  ['Animals', 'Which creature has the longest lifespan here?', 'Greenland shark', 'Elephant', 'Parrot', 'Tortoise'],
  ['Words', 'What is the opposite of "ancient"?', 'Modern', 'Old', 'Antique', 'Classic'],
  ['Words', 'Which word means "very happy"?', 'Elated', 'Morose', 'Sullen', 'Weary'],
  ['Words', 'How many letters are in the English alphabet?', '26', '24', '25', '28'],
  ['Words', 'What is a group of crows called?', 'A murder', 'A flock', 'A pack', 'A herd'],
  ['Words', 'Which is a palindrome?', 'Racecar', 'Rocket', 'Rotate', 'Ranger'],
  ['Words', '"Bonjour" means hello in which language?', 'French', 'Spanish', 'Italian', 'Portuguese'],
  ['Words', 'What does "LOL" stand for?', 'Laugh out loud', 'Lots of love', 'Look on line', 'Lame old laugh'],
  ['Words', 'Which word is spelled correctly?', 'Necessary', 'Neccesary', 'Necesary', 'Neccessary'],
];
